
Vagrant.configure("2") do |config|
  # Máquina
  config.vm.box = "centos/7"
  # Nome da máquina
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.2.2"
  # NFS = network file system / Precisa instalar o vbguest
  config.vm.synced_folder ".", "/vagrant", type: "nfs" 
  config.vm.provision "shell", path: "provision.sh"
end