
Vagrant.configure("2") do |config|
  # Máquina
  config.vm.box = "centos/7"
  # Nome da máquina
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.2.3"
  config.vm.network "forwarded_port", guest: 8080, host: 8080 
  # Para rodar quando subir a máquina e adicionar a key
  config.vm.provision "shell", path: "provision.sh"
end